//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab6.Data.DB.UsersSourceModelEF.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomBooking
    {
        public int booking_id { get; set; }
        public int user_id { get; set; }
        public int room_id { get; set; }
    
        public virtual room room { get; set; }
        public virtual User User { get; set; }
    }
}
