//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab6.Data.DB.UsersSourceModelEF.DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KpzLab6Entities2 : DbContext
    {
        public KpzLab6Entities2()
            : base("name=KpzLab6Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RoomBooking> RoomBookings { get; set; }
        public virtual DbSet<room> rooms { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
